/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  CollectionCreateRequest,
  CollectionUpdateRequest,
  GetMyCollectionsParams,
  PagedModelUserCollectionResponse,
  SearchCollectionsParams,
  UserCollectionResponse,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getCollections = () => {
  /**
   * @summary Search public collections
   */
  const searchCollections = (
    params?: SearchCollectionsParams,
    options?: SecondParameter<
      typeof customInstance<PagedModelUserCollectionResponse>
    >
  ) => {
    return customInstance<PagedModelUserCollectionResponse>(
      { url: `/api/v1/collections`, method: "GET", params },
      options
    )
  }
  /**
   * @summary Create collection
   */
  const createCollection = (
    collectionCreateRequest: CollectionCreateRequest,
    options?: SecondParameter<typeof customInstance<UserCollectionResponse>>
  ) => {
    return customInstance<UserCollectionResponse>(
      {
        url: `/api/v1/collections`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: collectionCreateRequest,
      },
      options
    )
  }
  /**
   * @summary Add a title to collection
   */
  const addTitleToCollection = (
    id: string,
    titleId: string,
    options?: SecondParameter<typeof customInstance<UserCollectionResponse>>
  ) => {
    return customInstance<UserCollectionResponse>(
      { url: `/api/v1/collections/${id}/titles/${titleId}`, method: "POST" },
      options
    )
  }
  /**
   * @summary Remove a title from collection
   */
  const removeTitleFromCollection = (
    id: string,
    titleId: string,
    options?: SecondParameter<typeof customInstance<UserCollectionResponse>>
  ) => {
    return customInstance<UserCollectionResponse>(
      { url: `/api/v1/collections/${id}/titles/${titleId}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Get collection
   */
  const getCollection = (
    id: string,
    options?: SecondParameter<typeof customInstance<UserCollectionResponse>>
  ) => {
    return customInstance<UserCollectionResponse>(
      { url: `/api/v1/collections/${id}`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete collection
   */
  const deleteCollection = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/collections/${id}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Update collection
   */
  const updateCollection = (
    id: string,
    collectionUpdateRequest: CollectionUpdateRequest,
    options?: SecondParameter<typeof customInstance<UserCollectionResponse>>
  ) => {
    return customInstance<UserCollectionResponse>(
      {
        url: `/api/v1/collections/${id}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: collectionUpdateRequest,
      },
      options
    )
  }
  /**
   * @summary Get my collections
   */
  const getMyCollections = (
    params?: GetMyCollectionsParams,
    options?: SecondParameter<typeof customInstance<UserCollectionResponse>>
  ) => {
    return customInstance<UserCollectionResponse>(
      { url: `/api/v1/collections/my`, method: "GET", params },
      options
    )
  }
  return {
    searchCollections,
    createCollection,
    addTitleToCollection,
    removeTitleFromCollection,
    getCollection,
    deleteCollection,
    updateCollection,
    getMyCollections,
  }
}
export type SearchCollectionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["searchCollections"]>>
>
export type CreateCollectionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["createCollection"]>>
>
export type AddTitleToCollectionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["addTitleToCollection"]>>
>
export type RemoveTitleFromCollectionResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getCollections>["removeTitleFromCollection"]>
  >
>
export type GetCollectionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["getCollection"]>>
>
export type DeleteCollectionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["deleteCollection"]>>
>
export type UpdateCollectionResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["updateCollection"]>>
>
export type GetMyCollectionsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCollections>["getMyCollections"]>>
>
