/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 2.0.0
 */
/**
 * RFC 9457 Problem Details
 */
export interface ProblemDetail {
  /** URI reference identifying the problem type */
  type?: unknown
  /** Short human-readable summary */
  title?: unknown
  /** HTTP status code */
  status?: unknown
  /** Human-readable explanation */
  detail?: unknown
  /** URI reference identifying the specific occurrence */
  instance?: unknown
}

export type LibraryEntryUpdateRequestStatus =
  (typeof LibraryEntryUpdateRequestStatus)[keyof typeof LibraryEntryUpdateRequestStatus]

export const LibraryEntryUpdateRequestStatus = {
  TO_READ: "TO_READ",
  READING: "READING",
  ON_HOLD: "ON_HOLD",
  DROPPED: "DROPPED",
  COMPLETED: "COMPLETED",
  RE_READING: "RE_READING",
} as const

export type LibraryEntryUpdateRequestVote =
  (typeof LibraryEntryUpdateRequestVote)[keyof typeof LibraryEntryUpdateRequestVote]

export const LibraryEntryUpdateRequestVote = {
  LIKE: "LIKE",
  DISLIKE: "DISLIKE",
} as const

export interface LibraryEntryUpdateRequest {
  status?: LibraryEntryUpdateRequestStatus
  vote?: LibraryEntryUpdateRequestVote
  lastReadChapterId?: string
}

export type LibraryEntryResponseStatus =
  (typeof LibraryEntryResponseStatus)[keyof typeof LibraryEntryResponseStatus]

export const LibraryEntryResponseStatus = {
  TO_READ: "TO_READ",
  READING: "READING",
  ON_HOLD: "ON_HOLD",
  DROPPED: "DROPPED",
  COMPLETED: "COMPLETED",
  RE_READING: "RE_READING",
} as const

export type LibraryEntryResponseVote =
  (typeof LibraryEntryResponseVote)[keyof typeof LibraryEntryResponseVote]

export const LibraryEntryResponseVote = {
  LIKE: "LIKE",
  DISLIKE: "DISLIKE",
} as const

export interface LibraryEntryResponse {
  id?: string
  userId?: string
  titleId?: string
  status?: LibraryEntryResponseStatus
  vote?: LibraryEntryResponseVote
  lastReadChapterId?: string
  createdAt?: string
  updatedAt?: string
}

export type TitleCreateRequestType =
  (typeof TitleCreateRequestType)[keyof typeof TitleCreateRequestType]

export const TitleCreateRequestType = {
  COMIC: "COMIC",
  MANGA: "MANGA",
  MANHWA: "MANHWA",
  MANHUA: "MANHUA",
  ARTBOOK: "ARTBOOK",
  NOVEL: "NOVEL",
} as const

export type TitleCreateRequestTitleStatus =
  (typeof TitleCreateRequestTitleStatus)[keyof typeof TitleCreateRequestTitleStatus]

export const TitleCreateRequestTitleStatus = {
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  ANNOUNCED: "ANNOUNCED",
  SUSPENDED: "SUSPENDED",
  DISCONTINUED: "DISCONTINUED",
} as const

export type TitleCreateRequestContentRating =
  (typeof TitleCreateRequestContentRating)[keyof typeof TitleCreateRequestContentRating]

export const TitleCreateRequestContentRating = {
  SIX_PLUS: "SIX_PLUS",
  TWELVE_PLUS: "TWELVE_PLUS",
  SIXTEEN_PLUS: "SIXTEEN_PLUS",
  EIGHTEEN_PLUS: "EIGHTEEN_PLUS",
} as const

export type TitleCreateRequestAuthorIds = {
  [key: string]: "STORY" | "ART" | "STORY_AND_ART"
}

export interface TitleCreateRequest {
  /** @minLength 1 */
  name: string
  slug?: string
  description?: string
  type: TitleCreateRequestType
  titleStatus: TitleCreateRequestTitleStatus
  releaseYear?: string
  contentRating: TitleCreateRequestContentRating
  /** @minLength 1 */
  countryIsoCode: string
  mainCoverMediaId?: string
  authorIds?: TitleCreateRequestAuthorIds
  publisherIds?: string[]
  tagIds?: string[]
}

export interface AuthorResponse {
  id?: string
  name?: string
  slug?: string
  description?: string
  websiteUrls?: string[]
  countryIsoCode?: string
  mainCoverMediaId?: string
}

export interface PublisherResponse {
  id?: string
  name?: string
  slug?: string
  description?: string
  websiteUrls?: string[]
  countryIsoCode?: string
  logoMediaId?: string
}

export type TagResponseType =
  (typeof TagResponseType)[keyof typeof TagResponseType]

export const TagResponseType = {
  CONTENT_WARNING: "CONTENT_WARNING",
  GENRE: "GENRE",
  THEME: "THEME",
} as const

export interface TagResponse {
  id?: string
  name?: string
  slug?: string
  type?: TagResponseType
  description?: string
}

export type TitleAuthorResponseRole =
  (typeof TitleAuthorResponseRole)[keyof typeof TitleAuthorResponseRole]

export const TitleAuthorResponseRole = {
  STORY: "STORY",
  ART: "ART",
  STORY_AND_ART: "STORY_AND_ART",
} as const

export interface TitleAuthorResponse {
  id?: string
  author?: AuthorResponse
  role?: TitleAuthorResponseRole
  sortOrder?: number
}

export interface TitlePublisherResponse {
  id?: string
  publisher?: PublisherResponse
  sortOrder?: number
}

export type TitleResponseType =
  (typeof TitleResponseType)[keyof typeof TitleResponseType]

export const TitleResponseType = {
  COMIC: "COMIC",
  MANGA: "MANGA",
  MANHWA: "MANHWA",
  MANHUA: "MANHUA",
  ARTBOOK: "ARTBOOK",
  NOVEL: "NOVEL",
} as const

export type TitleResponseTitleStatus =
  (typeof TitleResponseTitleStatus)[keyof typeof TitleResponseTitleStatus]

export const TitleResponseTitleStatus = {
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  ANNOUNCED: "ANNOUNCED",
  SUSPENDED: "SUSPENDED",
  DISCONTINUED: "DISCONTINUED",
} as const

export type TitleResponseContentRating =
  (typeof TitleResponseContentRating)[keyof typeof TitleResponseContentRating]

export const TitleResponseContentRating = {
  SIX_PLUS: "SIX_PLUS",
  TWELVE_PLUS: "TWELVE_PLUS",
  SIXTEEN_PLUS: "SIXTEEN_PLUS",
  EIGHTEEN_PLUS: "EIGHTEEN_PLUS",
} as const

export interface TitleResponse {
  id?: string
  name?: string
  slug?: string
  description?: string
  type?: TitleResponseType
  titleStatus?: TitleResponseTitleStatus
  releaseYear?: string
  contentRating?: TitleResponseContentRating
  isLicensed?: boolean
  countryIsoCode?: string
  mainCoverMediaId?: string
  authors?: TitleAuthorResponse[]
  publishers?: TitlePublisherResponse[]
  tags?: TagResponse[]
}

export interface ChapterCreateRequest {
  number: number
  subNumber: number
  name?: string
  volume?: number
  /** @minItems 1 */
  pages: string[]
}

export type TagCreateRequestType =
  (typeof TagCreateRequestType)[keyof typeof TagCreateRequestType]

export const TagCreateRequestType = {
  CONTENT_WARNING: "CONTENT_WARNING",
  GENRE: "GENRE",
  THEME: "THEME",
} as const

export interface TagCreateRequest {
  /** @minLength 1 */
  name: string
  slug?: string
  type: TagCreateRequestType
  description?: string
}

export interface PublisherCreateRequest {
  /** @minLength 1 */
  name: string
  slug?: string
  description?: string
  websiteUrls?: string[]
  countryIsoCode?: string
  logoMediaId?: string
}

export interface MediaUploadUrlRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  originalFilename: string
  /** @minLength 1 */
  contentType: string
  /** @maximum 4100 */
  width: number
  height: number
}

export interface MediaUploadUrlResponse {
  id?: string
  url?: string
  s3Key?: string
}

export interface CollectionCreateRequest {
  /** @minLength 1 */
  name: string
  description?: string
  isPublic: boolean
  titleIds?: string[]
}

export interface UserCollectionResponse {
  id?: string
  authorId?: string
  name?: string
  description?: string
  isPublic?: boolean
  titleIds?: string[]
  createdAt?: string
  updatedAt?: string
}

export interface ChapterReadRequest {
  readTimeMillis?: number
}

/**
 * Response containing next chapter information
 */
export interface NextChapterResponse {
  /** Next chapter unique identifier */
  chapterId?: string
  /** Next chapter display number */
  displayNumber?: string
  /** Next chapter name */
  name?: string
  /** Indicates if there is a next chapter available */
  hasNextChapter?: boolean
}

export interface AuthorCreateRequest {
  /** @minLength 1 */
  name: string
  slug?: string
  description?: string
  websiteUrls?: string[]
  /**
   * @minLength 2
   * @maxLength 2
   */
  countryIsoCode?: string
  mainCoverMediaId?: string
}

export type TitleUpdateRequestType =
  (typeof TitleUpdateRequestType)[keyof typeof TitleUpdateRequestType]

export const TitleUpdateRequestType = {
  COMIC: "COMIC",
  MANGA: "MANGA",
  MANHWA: "MANHWA",
  MANHUA: "MANHUA",
  ARTBOOK: "ARTBOOK",
  NOVEL: "NOVEL",
} as const

export type TitleUpdateRequestTitleStatus =
  (typeof TitleUpdateRequestTitleStatus)[keyof typeof TitleUpdateRequestTitleStatus]

export const TitleUpdateRequestTitleStatus = {
  ONGOING: "ONGOING",
  COMPLETED: "COMPLETED",
  ANNOUNCED: "ANNOUNCED",
  SUSPENDED: "SUSPENDED",
  DISCONTINUED: "DISCONTINUED",
} as const

export type TitleUpdateRequestContentRating =
  (typeof TitleUpdateRequestContentRating)[keyof typeof TitleUpdateRequestContentRating]

export const TitleUpdateRequestContentRating = {
  SIX_PLUS: "SIX_PLUS",
  TWELVE_PLUS: "TWELVE_PLUS",
  SIXTEEN_PLUS: "SIXTEEN_PLUS",
  EIGHTEEN_PLUS: "EIGHTEEN_PLUS",
} as const

export type TitleUpdateRequestAuthorIds = {
  [key: string]: "STORY" | "ART" | "STORY_AND_ART"
}

export interface TitleUpdateRequest {
  name?: string
  slug?: string
  description?: string
  type?: TitleUpdateRequestType
  titleStatus?: TitleUpdateRequestTitleStatus
  releaseYear?: string
  contentRating?: TitleUpdateRequestContentRating
  countryIsoCode?: string
  mainCoverMediaId?: string
  authorIds?: TitleUpdateRequestAuthorIds
  publisherIds?: string[]
  tagIds?: string[]
}

export type TagUpdateRequestType =
  (typeof TagUpdateRequestType)[keyof typeof TagUpdateRequestType]

export const TagUpdateRequestType = {
  CONTENT_WARNING: "CONTENT_WARNING",
  GENRE: "GENRE",
  THEME: "THEME",
} as const

export interface TagUpdateRequest {
  name?: string
  slug?: string
  type?: TagUpdateRequestType
  description?: string
}

export interface PublisherUpdateRequest {
  name?: string
  slug?: string
  description?: string
  websiteUrls?: string[]
  countryIsoCode?: string
  logoMediaId?: string
}

export interface CollectionUpdateRequest {
  name?: string
  description?: string
  isPublic?: boolean
  titleIds?: string[]
}

export interface ChapterUpdateRequest {
  number?: number
  subNumber?: number
  name?: string
  volume?: number
}

export interface AuthorUpdateRequest {
  name?: string
  slug?: string
  description?: string
  websiteUrls?: string[]
  countryIsoCode?: string
  mainCoverMediaId?: string
}

export interface PageMetadata {
  size?: number
  number?: number
  totalElements?: number
  totalPages?: number
}

export interface PagedModelTitleResponse {
  content?: TitleResponse[]
  page?: PageMetadata
}

export interface ChapterSummaryResponse {
  id?: string
  displayNumber?: string
  name?: string
  volume?: number
}

/**
 * Analytics data for a specific title
 */
export interface TitleAnalyticsResponse {
  /** Title unique identifier */
  titleId?: string
  /** Average rating of the title */
  averageRating?: number
  /** Number of unique readers */
  totalViews?: number
  /** Last updated timestamp */
  lastUpdated?: string
}

export interface PagedModelTagResponse {
  content?: TagResponse[]
  page?: PageMetadata
}

export interface PersonalRecommendationResponse {
  titleId?: string
  name?: string
  mainCoverMediaId?: string
  slug?: string
  score?: number
  reason?: string
}

export interface PagedModelPublisherResponse {
  content?: PublisherResponse[]
  page?: PageMetadata
}

export interface PagedModelLibraryEntryResponse {
  content?: LibraryEntryResponse[]
  page?: PageMetadata
}

export interface PagedModelUserCollectionResponse {
  content?: UserCollectionResponse[]
  page?: PageMetadata
}

export interface PageResponse {
  id?: string
  mediaId?: string
  url?: string
  pageOrder?: number
}

export interface ChapterDetailsResponse {
  id?: string
  titleId?: string
  displayNumber?: string
  name?: string
  pages?: PageResponse[]
  prevChapterId?: string
  nextChapterId?: string
}

/**
 * Chapter read status response
 */
export interface ChapterReadStatusResponse {
  /** Chapter unique identifier */
  chapterId?: string
  /** Status chapter is read */
  isRead?: boolean
}

export interface PagedModelAuthorResponse {
  content?: AuthorResponse[]
  page?: PageMetadata
}

/**
 * Weekly top title item
 */
export interface WeeklyPopularTitleResponse {
  /** Title unique identifier */
  titleId?: string
  /** Main cover media unique identifier */
  mainCoverMediaId?: string
  /** Title name */
  name?: string
  /** Title slug */
  slug?: string
  /** Views for the last 7 days */
  weeklyViews?: number
  /** Rank in top list */
  rank?: number
}

/**
 * Resource conflict (e.g., duplicate)
 */
export type ConflictResponse = ProblemDetail

/**
 * Insufficient permissions
 */
export type ForbiddenResponse = void

/**
 * Missing or invalid authentication token
 */
export type UnauthorizedResponse = void

/**
 * Resource not found
 */
export type NotFoundResponse = ProblemDetail

/**
 * Validation error or malformed request
 */
export type BadRequestResponse = ProblemDetail

/**
 * Unexpected server error
 */
export type InternalServerErrorResponse = ProblemDetail

export type SearchTitlesParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
  /**
   * Search text
   */
  search?: string
  /**
   * Filter by type
   */
  type?: string
  /**
   * Filter by status
   */
  titleStatus?: string
  /**
   * Filter by Country ISO Code
   */
  country?: string
  /**
   * Filter by tag UUIDs
   */
  tags?: string
  /**
   * Release year
   */
  releaseYear?: number
  /**
   * Min release year
   */
  yearFrom?: number
  /**
   * Max release year
   */
  yearTo?: number
  /**
   * Max content rating
   */
  contentRating?: string
}

export type GetTagsParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
}

export type SearchPublishersParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
  /**
   * Search by name or slug
   */
  search?: string
  /**
   * Filter by Country ISO Code
   */
  country?: string
}

export type SearchCollectionsParams = {
  /**
   * Search query
   */
  search?: string
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
}

export type SearchAuthorsParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
  /**
   * Search by name or slug
   */
  search?: string
  /**
   * Filter by Country ISO Code
   */
  country?: string
}

export type GetUserLibraryParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
}

export type GetMyRecommendationsParams = {
  /**
   * Max number of recommendations
   */
  limit?: number
}

export type GetMyLibraryParams = {
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
}

export type GetMyCollectionsParams = {
  /**
   * Search query
   */
  search?: string
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[]
}
