/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  TitleAnalyticsResponse,
  WeeklyPopularTitleResponse,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getAnalytics = () => {
  /**
   * @summary Get analytics for title
   */
  const getTitleAnalytics = (
    titleId: string,
    options?: SecondParameter<typeof customInstance<TitleAnalyticsResponse>>
  ) => {
    return customInstance<TitleAnalyticsResponse>(
      { url: `/api/v1/titles/${titleId}/analytics`, method: "GET" },
      options
    )
  }
  /**
   * @summary Get top 10 popular titles for the last 7 days
   */
  const getTopWeeklyPopularTitles = (
    options?: SecondParameter<
      typeof customInstance<WeeklyPopularTitleResponse[]>
    >
  ) => {
    return customInstance<WeeklyPopularTitleResponse[]>(
      { url: `/api/v1/analytics/titles/top-weekly`, method: "GET" },
      options
    )
  }
  return { getTitleAnalytics, getTopWeeklyPopularTitles }
}
export type GetTitleAnalyticsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAnalytics>["getTitleAnalytics"]>>
>
export type GetTopWeeklyPopularTitlesResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getAnalytics>["getTopWeeklyPopularTitles"]>
  >
>
