/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  ChapterCreateRequest,
  ChapterDetailsResponse,
  ChapterReadRequest,
  ChapterReadStatusResponse,
  ChapterSummaryResponse,
  ChapterUpdateRequest,
  NextChapterResponse,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getChapters = () => {
  /**
   * @summary Get chapters info for title
   */
  const getChaptersInfoByTitle = (
    titleId: string,
    options?: SecondParameter<typeof customInstance<ChapterSummaryResponse[]>>
  ) => {
    return customInstance<ChapterSummaryResponse[]>(
      { url: `/api/v1/titles/${titleId}/chapters`, method: "GET" },
      options
    )
  }
  /**
   * @summary Create chapter
   */
  const createChapter = (
    titleId: string,
    chapterCreateRequest: ChapterCreateRequest,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      {
        url: `/api/v1/titles/${titleId}/chapters`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: chapterCreateRequest,
      },
      options
    )
  }
  /**
   * @summary Record chapter as read and get next unread chapter
   */
  const recordChapterRead = (
    chapterId: string,
    chapterReadRequest: ChapterReadRequest,
    options?: SecondParameter<typeof customInstance<NextChapterResponse>>
  ) => {
    return customInstance<NextChapterResponse>(
      {
        url: `/api/v1/chapters/${chapterId}/read`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: chapterReadRequest,
      },
      options
    )
  }
  /**
   * @summary Get full chapter (including pages URLs)
   */
  const getFullChapter = (
    chapterId: string,
    options?: SecondParameter<typeof customInstance<ChapterDetailsResponse>>
  ) => {
    return customInstance<ChapterDetailsResponse>(
      { url: `/api/v1/chapters/${chapterId}`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete chapter
   */
  const deleteChapter = (
    chapterId: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/chapters/${chapterId}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Update chapter
   */
  const updateChapter = (
    chapterId: string,
    chapterUpdateRequest: ChapterUpdateRequest,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      {
        url: `/api/v1/chapters/${chapterId}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: chapterUpdateRequest,
      },
      options
    )
  }
  /**
   * @summary Get next unread chapter for a title
   */
  const getNextUnreadChapter = (
    titleId: string,
    options?: SecondParameter<typeof customInstance<NextChapterResponse>>
  ) => {
    return customInstance<NextChapterResponse>(
      { url: `/api/v1/titles/${titleId}/next-chapter`, method: "GET" },
      options
    )
  }
  /**
   * @summary Check if chapter has been read by current user
   */
  const isChapterRead = (
    chapterId: string,
    options?: SecondParameter<typeof customInstance<ChapterReadStatusResponse>>
  ) => {
    return customInstance<ChapterReadStatusResponse>(
      { url: `/api/v1/chapters/${chapterId}/read-status`, method: "GET" },
      options
    )
  }
  return {
    getChaptersInfoByTitle,
    createChapter,
    recordChapterRead,
    getFullChapter,
    deleteChapter,
    updateChapter,
    getNextUnreadChapter,
    isChapterRead,
  }
}
export type GetChaptersInfoByTitleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["getChaptersInfoByTitle"]>>
>
export type CreateChapterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["createChapter"]>>
>
export type RecordChapterReadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["recordChapterRead"]>>
>
export type GetFullChapterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["getFullChapter"]>>
>
export type DeleteChapterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["deleteChapter"]>>
>
export type UpdateChapterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["updateChapter"]>>
>
export type GetNextUnreadChapterResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["getNextUnreadChapter"]>>
>
export type IsChapterReadResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getChapters>["isChapterRead"]>>
>
