/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  PagedModelTitleResponse,
  SearchTitlesParams,
  TitleCreateRequest,
  TitleResponse,
  TitleUpdateRequest,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getTitles = () => {
  /**
   * @summary Search and filter titles
   */
  const searchTitles = (
    params?: SearchTitlesParams,
    options?: SecondParameter<typeof customInstance<PagedModelTitleResponse>>
  ) => {
    return customInstance<PagedModelTitleResponse>(
      { url: `/api/v1/titles`, method: "GET", params },
      options
    )
  }
  /**
   * @summary Create title
   */
  const createTitle = (
    titleCreateRequest: TitleCreateRequest,
    options?: SecondParameter<typeof customInstance<TitleResponse>>
  ) => {
    return customInstance<TitleResponse>(
      {
        url: `/api/v1/titles`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: titleCreateRequest,
      },
      options
    )
  }
  /**
   * @summary Get title
   */
  const getTitle = (
    id: string,
    options?: SecondParameter<typeof customInstance<TitleResponse>>
  ) => {
    return customInstance<TitleResponse>(
      { url: `/api/v1/titles/${id}`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete title
   */
  const deleteTitle = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/titles/${id}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Update title
   */
  const updateTitle = (
    id: string,
    titleUpdateRequest: TitleUpdateRequest,
    options?: SecondParameter<typeof customInstance<TitleResponse>>
  ) => {
    return customInstance<TitleResponse>(
      {
        url: `/api/v1/titles/${id}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: titleUpdateRequest,
      },
      options
    )
  }
  return { searchTitles, createTitle, getTitle, deleteTitle, updateTitle }
}
export type SearchTitlesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTitles>["searchTitles"]>>
>
export type CreateTitleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTitles>["createTitle"]>>
>
export type GetTitleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTitles>["getTitle"]>>
>
export type DeleteTitleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTitles>["deleteTitle"]>>
>
export type UpdateTitleResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTitles>["updateTitle"]>>
>
