/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  AuthorCreateRequest,
  AuthorResponse,
  AuthorUpdateRequest,
  PagedModelAuthorResponse,
  SearchAuthorsParams,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getAuthors = () => {
  /**
   * @summary Search and filter authors
   */
  const searchAuthors = (
    params?: SearchAuthorsParams,
    options?: SecondParameter<typeof customInstance<PagedModelAuthorResponse>>
  ) => {
    return customInstance<PagedModelAuthorResponse>(
      { url: `/api/v1/authors`, method: "GET", params },
      options
    )
  }
  /**
   * @summary Create author
   */
  const createAuthor = (
    authorCreateRequest: AuthorCreateRequest,
    options?: SecondParameter<typeof customInstance<AuthorResponse>>
  ) => {
    return customInstance<AuthorResponse>(
      {
        url: `/api/v1/authors`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: authorCreateRequest,
      },
      options
    )
  }
  /**
   * @summary Get author
   */
  const getAuthor = (
    id: string,
    options?: SecondParameter<typeof customInstance<AuthorResponse>>
  ) => {
    return customInstance<AuthorResponse>(
      { url: `/api/v1/authors/${id}`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete author
   */
  const deleteAuthor = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/authors/${id}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Update author
   */
  const updateAuthor = (
    id: string,
    authorUpdateRequest: AuthorUpdateRequest,
    options?: SecondParameter<typeof customInstance<AuthorResponse>>
  ) => {
    return customInstance<AuthorResponse>(
      {
        url: `/api/v1/authors/${id}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: authorUpdateRequest,
      },
      options
    )
  }
  return { searchAuthors, createAuthor, getAuthor, deleteAuthor, updateAuthor }
}
export type SearchAuthorsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthors>["searchAuthors"]>>
>
export type CreateAuthorResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthors>["createAuthor"]>>
>
export type GetAuthorResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthors>["getAuthor"]>>
>
export type DeleteAuthorResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthors>["deleteAuthor"]>>
>
export type UpdateAuthorResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuthors>["updateAuthor"]>>
>
