/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type { GetUserLibraryParams, LibraryEntryResponse } from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getUserLibrary = () => {
  /**
   * @summary Get user's public library
   */
  const getUserLibrary = (
    userId: string,
    params?: GetUserLibraryParams,
    options?: SecondParameter<typeof customInstance<LibraryEntryResponse>>
  ) => {
    return customInstance<LibraryEntryResponse>(
      { url: `/api/v1/users/${userId}/library`, method: "GET", params },
      options
    )
  }
  return { getUserLibrary }
}
export type GetUserLibraryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getUserLibrary>["getUserLibrary"]>>
>
