/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  MediaUploadUrlRequest,
  MediaUploadUrlResponse,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getMedia = () => {
  /**
   * @summary Get Upload Presigned URL
   */
  const generateUploadUrl = (
    mediaUploadUrlRequest: MediaUploadUrlRequest,
    options?: SecondParameter<typeof customInstance<MediaUploadUrlResponse>>
  ) => {
    return customInstance<MediaUploadUrlResponse>(
      {
        url: `/api/v1/media/upload-url`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: mediaUploadUrlRequest,
      },
      options
    )
  }
  /**
   * @summary Get Download Presigned URL
   */
  const getMediaUrl = (
    id: string,
    options?: SecondParameter<typeof customInstance<string>>
  ) => {
    return customInstance<string>(
      { url: `/api/v1/media/${id}/url`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete media
   */
  const deleteMedia = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/media/${id}`, method: "DELETE" },
      options
    )
  }
  return { generateUploadUrl, getMediaUrl, deleteMedia }
}
export type GenerateUploadUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMedia>["generateUploadUrl"]>>
>
export type GetMediaUrlResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMedia>["getMediaUrl"]>>
>
export type DeleteMediaResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getMedia>["deleteMedia"]>>
>
