/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  GetTagsParams,
  PagedModelTagResponse,
  TagCreateRequest,
  TagResponse,
  TagUpdateRequest,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getTags = () => {
  /**
   * @summary Get all tags
   */
  const getTags = (
    params?: GetTagsParams,
    options?: SecondParameter<typeof customInstance<PagedModelTagResponse>>
  ) => {
    return customInstance<PagedModelTagResponse>(
      { url: `/api/v1/tags`, method: "GET", params },
      options
    )
  }
  /**
   * @summary Create tag
   */
  const createTag = (
    tagCreateRequest: TagCreateRequest,
    options?: SecondParameter<typeof customInstance<TagResponse>>
  ) => {
    return customInstance<TagResponse>(
      {
        url: `/api/v1/tags`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: tagCreateRequest,
      },
      options
    )
  }
  /**
   * @summary Get tag
   */
  const getTag = (
    id: string,
    options?: SecondParameter<typeof customInstance<TagResponse>>
  ) => {
    return customInstance<TagResponse>(
      { url: `/api/v1/tags/${id}`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete tag
   */
  const deleteTag = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/tags/${id}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Update tag
   */
  const updateTag = (
    id: string,
    tagUpdateRequest: TagUpdateRequest,
    options?: SecondParameter<typeof customInstance<TagResponse>>
  ) => {
    return customInstance<TagResponse>(
      {
        url: `/api/v1/tags/${id}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: tagUpdateRequest,
      },
      options
    )
  }
  return { getTags, createTag, getTag, deleteTag, updateTag }
}
export type GetTagsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>["getTags"]>>
>
export type CreateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>["createTag"]>>
>
export type GetTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>["getTag"]>>
>
export type DeleteTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>["deleteTag"]>>
>
export type UpdateTagResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTags>["updateTag"]>>
>
