/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  GetMyRecommendationsParams,
  PersonalRecommendationResponse,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getRecommendations = () => {
  /**
   * @summary Get personal recommendations for current user
   */
  const getMyRecommendations = (
    params?: GetMyRecommendationsParams,
    options?: SecondParameter<
      typeof customInstance<PersonalRecommendationResponse[]>
    >
  ) => {
    return customInstance<PersonalRecommendationResponse[]>(
      { url: `/api/v1/recommendations/me`, method: "GET", params },
      options
    )
  }
  return { getMyRecommendations }
}
export type GetMyRecommendationsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getRecommendations>["getMyRecommendations"]>
  >
>
