/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Comics API
 * RESTful API for managing comics service.
 * OpenAPI spec version: 1.0.1
 */
import type {
  PagedModelPublisherResponse,
  PublisherCreateRequest,
  PublisherResponse,
  PublisherUpdateRequest,
  SearchPublishersParams,
} from "../api.schemas"

import { customInstance } from "../../axios-instance"

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

export const getPublishers = () => {
  /**
   * @summary Search and filter publishers
   */
  const searchPublishers = (
    params?: SearchPublishersParams,
    options?: SecondParameter<
      typeof customInstance<PagedModelPublisherResponse>
    >
  ) => {
    return customInstance<PagedModelPublisherResponse>(
      { url: `/api/v1/publishers`, method: "GET", params },
      options
    )
  }
  /**
   * @summary Create publisher
   */
  const createPublisher = (
    publisherCreateRequest: PublisherCreateRequest,
    options?: SecondParameter<typeof customInstance<PublisherResponse>>
  ) => {
    return customInstance<PublisherResponse>(
      {
        url: `/api/v1/publishers`,
        method: "POST",
        headers: { "Content-Type": "application/json" },
        data: publisherCreateRequest,
      },
      options
    )
  }
  /**
   * @summary Get publisher
   */
  const getPublisher = (
    id: string,
    options?: SecondParameter<typeof customInstance<PublisherResponse>>
  ) => {
    return customInstance<PublisherResponse>(
      { url: `/api/v1/publishers/${id}`, method: "GET" },
      options
    )
  }
  /**
   * @summary Delete publisher
   */
  const deletePublisher = (
    id: string,
    options?: SecondParameter<typeof customInstance<void>>
  ) => {
    return customInstance<void>(
      { url: `/api/v1/publishers/${id}`, method: "DELETE" },
      options
    )
  }
  /**
   * @summary Update publisher
   */
  const updatePublisher = (
    id: string,
    publisherUpdateRequest: PublisherUpdateRequest,
    options?: SecondParameter<typeof customInstance<PublisherResponse>>
  ) => {
    return customInstance<PublisherResponse>(
      {
        url: `/api/v1/publishers/${id}`,
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        data: publisherUpdateRequest,
      },
      options
    )
  }
  return {
    searchPublishers,
    createPublisher,
    getPublisher,
    deletePublisher,
    updatePublisher,
  }
}
export type SearchPublishersResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPublishers>["searchPublishers"]>>
>
export type CreatePublisherResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPublishers>["createPublisher"]>>
>
export type GetPublisherResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPublishers>["getPublisher"]>>
>
export type DeletePublisherResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPublishers>["deletePublisher"]>>
>
export type UpdatePublisherResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getPublishers>["updatePublisher"]>>
>
